using System.Collections.Generic;
using Unity.XR.CoreUtils;
using UnityEngine;
using UnityEngine.XR;

// Player avatar: smooth human hands on the controllers (fingers follow Grip / Trigger), a body with a work
// apron, and a head that only the studio mirror sees. Meshes: Assets/Resources/PM_Avatar/*.bytes
// (generated by tools/avatar). Choices are remembered between sessions.
public static class PM_Avatar
{
    public const int MirrorLayer = 30;   // the head is drawn only by the mirror camera

    public static int HandType { get; private set; }   // 0 man, 1 woman, 2 child (preview only)
    public static int Tone { get; private set; }
    public static int Tattoo { get; private set; }
    public static bool Hologram { get; private set; }
    public static int BodyType { get; private set; }   // 0 man, 1 woman
    public static int Outfit { get; private set; }

    static readonly Color[] Tones = { new Color(0.96f, 0.80f, 0.69f), new Color(0.87f, 0.67f, 0.53f), new Color(0.70f, 0.50f, 0.36f), new Color(0.42f, 0.28f, 0.20f) };
    static readonly string[] TattooNames = { null, "tattoo_needle", "tattoo_flower", "tattoo_geo" };
    // Outfits: shirt texture + tint, trousers texture + tint (textures: Resources/PM_Avatar/tex_*.png)
    static readonly string[] ShirtTex = { "tex_knit", "tex_knit", "tex_plaid", "tex_knit" };
    static readonly string[] PantsTex = { "tex_chino", "tex_denim", "tex_chino", "tex_denim" };
    static readonly Color[] ShirtTint = { new Color(0.24f, 0.24f, 0.27f), new Color(0.96f, 0.96f, 0.97f), Color.white, new Color(0.55f, 0.1f, 0.18f) };
    static readonly Color[] PantsTint = { new Color(0.22f, 0.22f, 0.24f), Color.white, new Color(0.2f, 0.2f, 0.22f), Color.white };
    // Shoes: upper, sole, accent (laces / stripe / buckle)
    static readonly string[] ShoeKeys = { "shoes_sneaker", "shoes_boot", "shoes_classic" };
    static readonly Color[,] ShoeCols =
    {
        { new Color(0.95f, 0.95f, 0.96f), new Color(0.85f, 0.86f, 0.88f), new Color(0.1f, 0.95f, 1f) },
        { new Color(0.45f, 0.27f, 0.14f), new Color(0.12f, 0.1f, 0.09f), new Color(0.78f, 0.62f, 0.4f) },
        { new Color(0.07f, 0.07f, 0.08f), new Color(0.22f, 0.13f, 0.07f), new Color(0.8f, 0.8f, 0.82f) },
    };
    public static int Shoes { get; private set; }
    // Humanoid characters from the Inspector (PM_Game → Avatar Characters). -1 = hands only,
    // -2 = the avatar that a loader puts into the scene (Genies); hands until it appears.
    public const int SceneCharacter = -2;
    public static GameObject[] Characters = new GameObject[0];
    public static bool AdoptSceneCharacter = true;   // use a Humanoid avatar that appears in the scene (e.g. Genies)
    static Transform ctrlL, ctrlR, xrRoot;
    public static int Character { get; private set; } = SceneCharacter;
    public static void ChooseCharacter(int c)
    {
        Character = c == SceneCharacter || (Characters != null && c >= 0 && c < Characters.Length) ? c : -1;
        Save();
    }
    static GameObject humanoid, adopted;
    public static bool SceneCharacterAvailable { get { return AdoptSceneCharacter && (adopted != null || PM_Humanoid.FindSceneCharacter() != null); } }

    static Material skin, nail, shirt, pants, shoes, apron, hair, eyes, holo, sleeve, shoeUpper, shoeSole, shoeAccent;
    static PM_Hand leftHand, rightHand;
    static PM_Body body;
    static Transform preview;
    static PM_AvatarRig rig;

    public static void Init()
    {
        skin = Lit(Tones[0], 0.38f);
        nail = Lit(Color.white, 0.75f);
        shirt = Lit(Color.gray, 0.2f);
        pants = Lit(Color.gray, 0.15f);
        shoes = Lit(new Color(0.05f, 0.05f, 0.06f), 0.55f);
        sleeve = Lit(Color.gray, 0.2f);
        shoeUpper = Lit(Color.white, 0.45f);
        shoeSole = Lit(Color.gray, 0.2f);
        shoeAccent = Lit(Color.white, 0.5f);
        apron = Lit(new Color(0.07f, 0.24f, 0.29f), 0.3f);
        Tex(apron, "tex_canvas", 1f);
        hair = Lit(new Color(0.25f, 0.16f, 0.09f), 0.35f);
        eyes = Lit(new Color(0.07f, 0.07f, 0.09f), 0.9f);
        holo = PM_Util.TransparentMaterial(new Color(0.3f, 0.95f, 1f, 0.35f));
        HandType = Mathf.Clamp(PlayerPrefs.GetInt("PM_Hand", 0), 0, 1);
        Tone = Mathf.Clamp(PlayerPrefs.GetInt("PM_Tone", 0), 0, 3);
        Tattoo = Mathf.Clamp(PlayerPrefs.GetInt("PM_Tattoo", 0), 0, 3);
        Hologram = PlayerPrefs.GetInt("PM_Holo", 0) == 1;
        BodyType = Mathf.Clamp(PlayerPrefs.GetInt("PM_Body", 0), 0, 1);
        Outfit = Mathf.Clamp(PlayerPrefs.GetInt("PM_Outfit", 0), 0, 3);
        Shoes = Mathf.Clamp(PlayerPrefs.GetInt("PM_Shoes", 0), 0, 2);
        Character = PlayerPrefs.GetInt("PM_Char2", SceneCharacter);
        if (Character < SceneCharacter || Characters == null || Character >= Characters.Length || (Character >= 0 && Characters[Character] == null)) Character = -1;
        ApplyMaterials();
        rig = new GameObject("PM_AvatarRig").AddComponent<PM_AvatarRig>();
    }

    static Material Lit(Color c, float smooth)
    {
        var m = new Material(PM_Util.LitShader());
        m.SetColor("_BaseColor", c);
        m.SetColor("_Color", c);
        m.SetFloat("_Smoothness", smooth);
        return m;
    }

    static void SetColor(Material m, Color c) { m.SetColor("_BaseColor", c); m.SetColor("_Color", c); }

    static void Tex(Material m, string name, float tiling)
    {
        Texture2D t = Resources.Load<Texture2D>("PM_Avatar/" + name);
        if (t == null) return;
        t.wrapMode = TextureWrapMode.Repeat;
        m.SetTexture("_BaseMap", t); m.SetTexture("_MainTex", t);
        m.SetTextureScale("_BaseMap", new Vector2(tiling, tiling)); m.SetTextureScale("_MainTex", new Vector2(tiling, tiling));
    }

    static void ApplyMaterials()
    {
        Color tone = Tones[Tone];
        SetColor(skin, tone);
        Texture2D tex = TattooNames[Tattoo] != null ? Resources.Load<Texture2D>("PM_Avatar/" + TattooNames[Tattoo]) : null;
        if (tex != null) tex.wrapMode = TextureWrapMode.Clamp;
        skin.SetTexture("_BaseMap", tex != null ? tex : Texture2D.whiteTexture);
        skin.SetTexture("_MainTex", tex != null ? tex : Texture2D.whiteTexture);
        if (HandType == 1) { SetColor(nail, new Color(0.72f, 0.08f, 0.24f)); nail.SetFloat("_Smoothness", 0.9f); }
        else { SetColor(nail, Color.Lerp(tone, new Color(1f, 0.82f, 0.82f), 0.45f)); nail.SetFloat("_Smoothness", 0.6f); }
        SetColor(shirt, ShirtTint[Outfit]); Tex(shirt, ShirtTex[Outfit], 1f);
        SetColor(sleeve, ShirtTint[Outfit]); Tex(sleeve, ShirtTex[Outfit], 2.5f);   // arm tubes: unit UVs, so tile more
        SetColor(pants, PantsTint[Outfit]); Tex(pants, PantsTex[Outfit], 1f);
        SetColor(shoeUpper, ShoeCols[Shoes, 0]); SetColor(shoeSole, ShoeCols[Shoes, 1]); SetColor(shoeAccent, ShoeCols[Shoes, 2]);
        Tex(shoeUpper, Shoes == 0 ? "tex_canvas" : "tex_leather", 2f);
        shoeUpper.SetFloat("_Smoothness", Shoes == 2 ? 0.85f : 0.4f);
        if (Shoes == 0) { shoeAccent.EnableKeyword("_EMISSION"); shoeAccent.SetColor("_EmissionColor", PM_Util.Cyan * 0.8f); }
        else { shoeAccent.DisableKeyword("_EMISSION"); shoeAccent.SetColor("_EmissionColor", Color.black); }
        shoeAccent.SetFloat("_Metallic", Shoes == 2 ? 0.8f : 0f);
    }

    public static Material[] HandMaterials() { return Hologram ? new[] { holo, holo } : new[] { skin, nail }; }
    public static Material ShirtMaterial() { return Hologram ? holo : sleeve; }
    public static Material[] ShoeMaterials() { return Hologram ? new[] { holo, holo, holo } : new[] { shoeUpper, shoeSole, shoeAccent }; }
    public static string ShoeKey() { return ShoeKeys[Shoes]; }
    // Body submeshes: 0 skin, 1 shirt, 2 pants, 3 shoes, 4 apron, 5 hair, 6 eyes
    public static Material[] BodyMaterials()
    {
        if (Hologram) return new[] { holo, holo, holo, holo, holo, holo, holo };
        return new[] { skin, shirt, pants, shoes, apron, hair, eyes };
    }
    static string HandKey(int t) { return t == 1 ? "woman" : t == 2 ? "child" : "man"; }
    public static string BodyKey() { return BodyType == 1 ? "woman" : "man"; }

    // ----- choices -----
    public static void ChooseHands(int type)   // 0 man, 1 woman, 3 hologram (2 = child is refused by the game)
    {
        if (type == 3) Hologram = true;
        else { Hologram = false; HandType = Mathf.Clamp(type, 0, 1); BodyType = HandType; }
        Save();
    }
    public static void ChooseTone(int t) { Tone = Mathf.Clamp(t, 0, 3); Hologram = false; Save(); }
    public static void ChooseTattoo(int t) { Tattoo = Mathf.Clamp(t, 0, 3); Save(); }
    public static void ChooseBody(int b) { BodyType = Mathf.Clamp(b, 0, 1); Save(); }
    public static void ChooseOutfit(int o) { Outfit = Mathf.Clamp(o, 0, 3); Save(); }
    public static void ChooseShoes(int o) { Shoes = Mathf.Clamp(o, 0, 2); Save(); }

    static void Save()
    {
        PlayerPrefs.SetInt("PM_Hand", HandType); PlayerPrefs.SetInt("PM_Tone", Tone); PlayerPrefs.SetInt("PM_Tattoo", Tattoo);
        PlayerPrefs.SetInt("PM_Holo", Hologram ? 1 : 0); PlayerPrefs.SetInt("PM_Body", BodyType); PlayerPrefs.SetInt("PM_Outfit", Outfit); PlayerPrefs.SetInt("PM_Shoes", Shoes); PlayerPrefs.SetInt("PM_Char2", Character);
        ApplyMaterials();
        if (rig != null) rig.Rebuild();
        RefreshPreview();
    }

    // ----- in the headset -----
    // Called every frame by the rig until the controllers exist (XR may start a few frames after Play).
    public static bool TryBuild()
    {
        if (!XRSettings.isDeviceActive) return false;
        XROrigin origin = Object.FindAnyObjectByType<XROrigin>();
        if (origin == null || origin.CameraFloorOffsetObject == null) return false;
        Transform offset = origin.CameraFloorOffsetObject.transform;
        Transform left = null, right = null;
        foreach (Transform c in offset.GetComponentsInChildren<Transform>(true))
        {
            if (c.parent != offset) continue;
            string n = c.name.ToLower();
            if (!n.Contains("controller") && !n.Contains("hand")) continue;
            if (!c.gameObject.activeInHierarchy) continue;
            // "Left Controller" rather than "Left Controller Teleport Stabilized Origin": the shortest name wins.
            if (n.Contains("left") && (left == null || c.name.Length < left.name.Length)) left = c;
            else if (n.Contains("right") && (right == null || c.name.Length < right.name.Length)) right = c;
        }
        if (left == null || right == null) return false;
        if (PM_HandData.Get(HandKey(HandType), false) == null) return true;   // no hand files: keep the controllers
        Clear();
        HideControllerModel(left);
        HideControllerModel(right);
        ctrlL = left; ctrlR = right; xrRoot = origin.transform;
        if (Character >= 0)
        {
            // A Humanoid character: its own hands follow the controllers, its body stands under the eyes.
            humanoid = PM_Humanoid.Create(Characters[Character], origin.transform, left, right);
            if (humanoid != null) return true;
        }
        // Hands only (the simple body is switched off: it looked broken when moving).
        leftHand = PM_Hand.Create(left, true, HandKey(HandType), true);
        rightHand = PM_Hand.Create(right, false, HandKey(HandType), true);
        return leftHand != null && rightHand != null;
    }

    static void Clear()
    {
        if (leftHand != null) Object.Destroy(leftHand.gameObject);
        if (rightHand != null) Object.Destroy(rightHand.gameObject);
        if (body != null) Object.Destroy(body.gameObject);
        if (humanoid != null && humanoid == adopted) humanoid.SetActive(false);   // a scene avatar is kept for later
        else if (humanoid != null) Object.Destroy(humanoid);
        leftHand = rightHand = null; body = null; humanoid = null;
    }

    static void HideControllerModel(Transform controller)
    {
        foreach (Renderer r in controller.GetComponentsInChildren<Renderer>(true))
        {
            if (r is LineRenderer || r is ParticleSystemRenderer) continue;          // keep the pointing ray
            if (r.GetComponentInParent<PM_Hand>() != null) continue;
            r.enabled = false;
        }
    }

    // Called by the rig every second: a Humanoid avatar loaded into the scene (Genies etc.) becomes the body.
    public static void CheckSceneCharacter()
    {
        if (!AdoptSceneCharacter || Character != SceneCharacter || humanoid != null || ctrlL == null || ctrlR == null) return;
        GameObject go = adopted;
        if (go != null) go.SetActive(true);
        else
        {
            Animator a = PM_Humanoid.FindSceneCharacter();
            if (a == null) return;
            go = PM_Humanoid.Adopt(a, xrRoot, ctrlL, ctrlR);
            if (go == null) return;
            adopted = go;
        }
        if (leftHand != null) Object.Destroy(leftHand.gameObject);
        if (rightHand != null) Object.Destroy(rightHand.gameObject);
        leftHand = rightHand = null;
        humanoid = go;
    }

    // ----- preview next to the menu (works also without the headset) -----
    static int previewMode;          // 0 none, 1 hands, 2 body
    static int previewHandType = -1; // -1 = the chosen hands, 2 = child (shown with the warning)
    static Vector3 previewPos, previewViewer;

    public static void ShowPreview(int mode, Vector3 pos, Vector3 viewer, int handTypeOverride = -1)
    {
        previewMode = mode; previewPos = pos; previewViewer = viewer; previewHandType = handTypeOverride;
        RefreshPreview();
    }

    static void RefreshPreview()
    {
        if (preview != null) Object.Destroy(preview.gameObject);
        preview = null;
        if (previewMode == 0) return;
        preview = new GameObject("PM_AvatarPreview").transform;
        preview.position = previewPos;
        Vector3 d = previewPos - previewViewer; d.y = 0;
        preview.rotation = Quaternion.LookRotation(d.sqrMagnitude > 0.001f ? d : Vector3.forward, Vector3.up);   // looks away from the viewer
        if (previewMode == 1)
        {
            string key = HandKey(previewHandType >= 0 ? previewHandType : HandType);
            PM_Hand l = PM_Hand.Create(preview, true, key, false);
            PM_Hand r = PM_Hand.Create(preview, false, key, false);
            if (l == null || r == null) return;
            // Fingers up, backs of the hands towards the viewer.
            l.transform.localPosition = new Vector3(-0.1f, -0.05f, 0);
            r.transform.localPosition = new Vector3(0.1f, -0.05f, 0);
            l.transform.localRotation = Quaternion.LookRotation(Vector3.up, Vector3.right);
            r.transform.localRotation = Quaternion.LookRotation(Vector3.up, -Vector3.right);
            preview.localScale = Vector3.one * 1.6f;
            preview.gameObject.AddComponent<PM_Float>().amplitude = 0.015f;
        }
        else
        {
            // Small figure that turns slowly (head included).
            var spin = new GameObject("Spin").transform;
            spin.SetParent(preview, false);
            spin.localRotation = Quaternion.Euler(0, 180, 0);
            PM_Body.Figure(spin, BodyKey(), true);
            spin.gameObject.AddComponent<PM_Spin>();
            preview.localScale = Vector3.one * 0.42f;
        }
    }
}

public class PM_Spin : MonoBehaviour
{
    void Update() { transform.Rotate(0, 25f * Time.deltaTime, 0, Space.Self); }
}

// Watches for the headset/controllers and (re)builds the hands and the body.
public class PM_AvatarRig : MonoBehaviour
{
    bool built;
    float nextTry;
    public void Rebuild() { built = false; nextTry = 0f; }
    float nextScan;
    void Update()
    {
        if (built && Time.unscaledTime > nextScan) { nextScan = Time.unscaledTime + 1f; PM_Avatar.CheckSceneCharacter(); }
        if (built || Time.unscaledTime < nextTry) return;
        nextTry = Time.unscaledTime + 0.5f;
        built = PM_Avatar.TryBuild();
        if (built) Debug.Log("[PM] Руки и тело аватара созданы.");
    }
}

// Mesh data of a hand (right hand; the left one is mirrored).
public class PM_HandData
{
    public Vector3[] v, n; public Vector2[] uv; public BoneWeight[] w; public int[] skin, nails;
    public Vector3[] joints, axes; public int[] parents;
    static readonly Dictionary<string, PM_HandData> cache = new Dictionary<string, PM_HandData>();

    public static PM_HandData Get(string key, bool left)
    {
        string k = key + (left ? "_L" : "_R");
        PM_HandData d;
        if (cache.TryGetValue(k, out d)) return d;
        TextAsset ta = Resources.Load<TextAsset>("PM_Avatar/hand_" + key);
        if (ta == null) { Debug.LogWarning("[PM] Нет файла руки: Assets/Resources/PM_Avatar/hand_" + key + ".bytes"); return null; }
        d = Parse(ta.bytes, left);
        cache[k] = d;
        return d;
    }

    static PM_HandData Parse(byte[] b, bool left)
    {
        var r = new System.IO.BinaryReader(new System.IO.MemoryStream(b));
        r.ReadInt32();
        int vc = r.ReadInt32(), sc = r.ReadInt32(), nc = r.ReadInt32(), jc = r.ReadInt32();
        float sx = left ? -1f : 1f;
        var d = new PM_HandData { joints = new Vector3[jc], axes = new Vector3[jc], parents = new int[jc] };
        for (int i = 0; i < jc; i++)
        {
            d.parents[i] = r.ReadInt32();
            d.joints[i] = new Vector3(r.ReadSingle() * sx, r.ReadSingle(), r.ReadSingle());
            Vector3 a = new Vector3(r.ReadSingle(), r.ReadSingle(), r.ReadSingle());
            d.axes[i] = left ? new Vector3(a.x, -a.y, -a.z) : a;   // mirrored rotation axis
        }
        d.v = new Vector3[vc]; d.n = new Vector3[vc]; d.uv = new Vector2[vc]; d.w = new BoneWeight[vc];
        for (int i = 0; i < vc; i++) d.v[i] = new Vector3(r.ReadSingle() * sx, r.ReadSingle(), r.ReadSingle());
        for (int i = 0; i < vc; i++) d.n[i] = new Vector3(r.ReadSingle() * sx, r.ReadSingle(), r.ReadSingle());
        for (int i = 0; i < vc; i++) d.uv[i] = new Vector2(r.ReadSingle(), r.ReadSingle());
        var idx = new int[vc * 2];
        for (int i = 0; i < vc * 2; i++) idx[i] = r.ReadInt32();
        for (int i = 0; i < vc; i++)
        {
            float w0 = r.ReadSingle(), w1 = r.ReadSingle();
            d.w[i] = new BoneWeight { boneIndex0 = idx[i * 2], weight0 = w0, boneIndex1 = idx[i * 2 + 1], weight1 = w1 };
        }
        d.skin = new int[sc]; for (int i = 0; i < sc; i++) d.skin[i] = r.ReadInt32();
        d.nails = new int[nc]; for (int i = 0; i < nc; i++) d.nails[i] = r.ReadInt32();
        if (left) { Flip(d.skin); Flip(d.nails); }   // mirroring turns the triangles inside out
        return d;
    }

    static void Flip(int[] t) { for (int i = 0; i < t.Length; i += 3) { int x = t[i + 1]; t[i + 1] = t[i + 2]; t[i + 2] = x; } }
}

// Human hand on a controller (grip pose): fingers forward (+Z), thumb up (+Y), palm facing inwards.
// While it holds the iron, the hand sits on the iron's handle (so it never goes through the iron or the board).
[DefaultExecutionOrder(200)]
public class PM_Hand : MonoBehaviour
{
    public bool left;
    public Transform Wrist { get; private set; }
    bool live;
    Vector3 home;
    Transform[] bones;
    Vector3[] axes;
    float grip, trigger;

    public static PM_Hand Create(Transform parent, bool left, string key, bool live)
    {
        PM_HandData d = PM_HandData.Get(key, left);
        if (d == null) return null;
        var go = new GameObject(left ? "PM_LeftHand" : "PM_RightHand");
        go.transform.SetParent(parent, false);
        float s = left ? -1f : 1f;
        // The controller handle sits inside the closed fist.
        if (live) go.transform.localPosition = new Vector3(0.026f * s, 0.006f, 0.035f);
        var h = go.AddComponent<PM_Hand>();
        h.home = go.transform.localPosition;
        h.left = left;
        h.live = live;
        h.Build(d);
        return h;
    }

    void Build(PM_HandData d)
    {
        int jc = d.joints.Length;
        bones = new Transform[jc];
        axes = d.axes;
        for (int i = 0; i < jc; i++)
        {
            bones[i] = new GameObject("J" + i).transform;
            Transform p = d.parents[i] >= 0 ? bones[d.parents[i]] : transform;
            bones[i].SetParent(p, false);
            bones[i].localPosition = d.joints[i] - (d.parents[i] >= 0 ? d.joints[d.parents[i]] : Vector3.zero);
        }
        var bind = new Matrix4x4[jc];
        for (int i = 0; i < jc; i++) bind[i] = bones[i].worldToLocalMatrix * transform.localToWorldMatrix;

        var mesh = new Mesh();
        mesh.name = "PM_Hand";
        if (d.v.Length > 65000) mesh.indexFormat = UnityEngine.Rendering.IndexFormat.UInt32;
        mesh.vertices = d.v;
        mesh.normals = d.n;
        mesh.uv = d.uv;
        var white = new Color32[d.v.Length];
        for (int i = 0; i < white.Length; i++) white[i] = new Color32(255, 255, 255, 255);
        mesh.colors32 = white;
        mesh.boneWeights = d.w;
        mesh.bindposes = bind;
        mesh.subMeshCount = 2;
        mesh.SetTriangles(d.skin, 0);
        mesh.SetTriangles(d.nails, 1);
        mesh.RecalculateBounds();

        var smr = gameObject.AddComponent<SkinnedMeshRenderer>();
        smr.sharedMesh = mesh;
        smr.bones = bones;
        smr.rootBone = bones[0];
        smr.sharedMaterials = PM_Avatar.HandMaterials();
        smr.updateWhenOffscreen = true;
        smr.shadowCastingMode = UnityEngine.Rendering.ShadowCastingMode.Off;

        float s = left ? -1f : 1f;
        Wrist = new GameObject("Wrist").transform;
        Wrist.SetParent(transform, false);
        Wrist.localPosition = d.joints[0] + new Vector3(0.012f * s, -0.006f, -0.15f);
        if (live)
        {
            // Shirt cuff over the end of the forearm.
            var cuff = GameObject.CreatePrimitive(PrimitiveType.Cylinder);
            Destroy(cuff.GetComponent<Collider>());
            cuff.transform.SetParent(transform, false);
            cuff.transform.localPosition = new Vector3(0.012f * s, -0.006f, -0.185f);
            cuff.transform.localRotation = Quaternion.Euler(90, 0, 0);
            cuff.transform.localScale = new Vector3(0.062f, 0.03f, 0.058f);
            var cr = cuff.GetComponent<Renderer>();
            cr.sharedMaterial = PM_Avatar.ShirtMaterial();
            cr.shadowCastingMode = UnityEngine.Rendering.ShadowCastingMode.Off;
        }
        Pose(0.15f, 0.1f);
    }

    // g = grip (middle, ring, pinky, thumb), t = trigger (index finger). 0 = open, 1 = fist.
    void Pose(float g, float t)
    {
        float[] maxA = { 62f, 92f, 60f };
        for (int f = 1; f <= 4; f++)
        {
            float c = f == 1 ? t : g;
            for (int j = 0; j < 3; j++)
            {
                int b = 1 + f * 3 + j;
                bones[b].localRotation = Quaternion.AngleAxis(maxA[j] * c, axes[b]);
            }
        }
        bones[2].localRotation = Quaternion.AngleAxis(18f * g, axes[2]);
        bones[3].localRotation = Quaternion.AngleAxis(28f * g, axes[3]);
    }

    void Update()
    {
        if (!live) return;
        InputDevice d = InputDevices.GetDeviceAtXRNode(left ? XRNode.LeftHand : XRNode.RightHand);
        float g = 0f, t = 0f;
        if (d.isValid)
        {
            d.TryGetFeatureValue(CommonUsages.grip, out g);
            d.TryGetFeatureValue(CommonUsages.trigger, out t);
        }
        grip = Mathf.Lerp(grip, g, Time.deltaTime * 18f);
        trigger = Mathf.Lerp(trigger, t, Time.deltaTime * 18f);
        Pose(0.1f + grip * 0.9f, 0.08f + trigger * 0.92f);
    }

    void LateUpdate()
    {
        if (!live) return;
        Vector3 p; Quaternion r;
        if (PM_Iron.HandleGrip(left, out p, out r))
        {
            transform.rotation = r;
            transform.position = p + r * home;
        }
        else
        {
            transform.localPosition = home;
            transform.localRotation = Quaternion.identity;
        }
    }
}

// Body (and the head for the mirror) under the player's eyes; arms reach the hands.
public class PM_Body : MonoBehaviour
{
    Transform head, figure;
    PM_Hand lh, rh;
    readonly Transform[] arm = new Transform[4];
    Transform origin;
    float yaw, eyeModel = 1.6f, eyeReal = 1.0f;
    Vector3 shoulder;

    // Loads body + head meshes under parent (feet at the parent origin). Returns eye height and shoulder offset.
    public static float Figure(Transform parent, string key, bool headVisible)
    {
        float eye = 1.6f;
        Mesh b = Load("body_" + key, out eye, out Vector3 sh);
        Mesh h = Load("head_" + key, out float _, out Vector3 __);
        Material[] mats = PM_Avatar.BodyMaterials();
        if (b != null) Part(parent, "Body", b, mats, 0);
        if (h != null) Part(parent, "Head", h, mats, headVisible ? 0 : PM_Avatar.MirrorLayer);
        Mesh sh2 = Load(PM_Avatar.ShoeKey(), out float ___, out Vector3 ____);
        if (sh2 != null) Part(parent, "Shoes", sh2, PM_Avatar.ShoeMaterials(), 0);
        return eye;
    }

    static void Part(Transform parent, string name, Mesh m, Material[] mats, int layer)
    {
        var go = new GameObject(name);
        go.layer = layer;
        go.transform.SetParent(parent, false);
        go.AddComponent<MeshFilter>().sharedMesh = m;
        var r = go.AddComponent<MeshRenderer>();
        var use = new Material[m.subMeshCount];
        for (int i = 0; i < use.Length; i++) use[i] = mats[Mathf.Min(i, mats.Length - 1)];
        r.sharedMaterials = use;
        r.shadowCastingMode = UnityEngine.Rendering.ShadowCastingMode.Off;
    }

    static readonly Dictionary<string, Mesh> meshes = new Dictionary<string, Mesh>();
    static readonly Dictionary<string, Vector4> info = new Dictionary<string, Vector4>();

    static Mesh Load(string name, out float eye, out Vector3 shoulder)
    {
        eye = 1.6f; shoulder = new Vector3(0.21f, 1.4f, 0f);
        Mesh m;
        Vector4 inf;
        if (meshes.TryGetValue(name, out m) && info.TryGetValue(name, out inf))
        {
            eye = inf.w; shoulder = new Vector3(inf.x, inf.y, inf.z);
            return m;
        }
        TextAsset ta = Resources.Load<TextAsset>("PM_Avatar/" + name);
        if (ta == null) { Debug.LogWarning("[PM] Нет файла аватара: " + name); return null; }
        var r = new System.IO.BinaryReader(new System.IO.MemoryStream(ta.bytes));
        bool hasUV = r.ReadInt32() == 0x504D4D32;   // version 2 files carry texture coordinates
        int vc = r.ReadInt32(), ns = r.ReadInt32();
        eye = r.ReadSingle();
        shoulder = new Vector3(r.ReadSingle(), r.ReadSingle(), r.ReadSingle());
        var counts = new int[ns];
        for (int i = 0; i < ns; i++) counts[i] = r.ReadInt32();
        var v = new Vector3[vc]; var n = new Vector3[vc];
        for (int i = 0; i < vc; i++) v[i] = new Vector3(r.ReadSingle(), r.ReadSingle(), r.ReadSingle());
        for (int i = 0; i < vc; i++) n[i] = new Vector3(r.ReadSingle(), r.ReadSingle(), r.ReadSingle());
        Vector2[] uv = null;
        if (hasUV) { uv = new Vector2[vc]; for (int i = 0; i < vc; i++) uv[i] = new Vector2(r.ReadSingle(), r.ReadSingle()); }
        m = new Mesh { name = name };
        if (vc > 65000) m.indexFormat = UnityEngine.Rendering.IndexFormat.UInt32;
        m.vertices = v; m.normals = n;
        if (uv != null) m.uv = uv;
        var white = new Color32[vc];
        for (int i = 0; i < vc; i++) white[i] = new Color32(255, 255, 255, 255);
        m.colors32 = white;
        m.subMeshCount = ns;
        for (int s = 0; s < ns; s++)
        {
            var t = new int[counts[s]];
            for (int i = 0; i < t.Length; i++) t[i] = r.ReadInt32();
            m.SetTriangles(t, s);
        }
        m.RecalculateBounds();
        meshes[name] = m;
        info[name] = new Vector4(shoulder.x, shoulder.y, shoulder.z, eye);
        return m;
    }

    public static PM_Body Create(Transform xrOrigin, PM_Hand l, PM_Hand r)
    {
        var go = new GameObject("PM_Body");
        var b = go.AddComponent<PM_Body>();
        b.origin = xrOrigin;
        b.lh = l; b.rh = r;
        b.head = Camera.main != null ? Camera.main.transform : null;
        b.figure = new GameObject("Figure").transform;
        b.figure.SetParent(go.transform, false);
        b.eyeModel = Figure(b.figure, PM_Avatar.BodyKey(), false);
        Vector4 inf;
        b.shoulder = info.TryGetValue("body_" + PM_Avatar.BodyKey(), out inf) ? new Vector3(inf.x, inf.y, inf.z) : new Vector3(0.21f, 1.4f, 0);
        for (int i = 0; i < 4; i++)
        {
            var c = GameObject.CreatePrimitive(PrimitiveType.Capsule);
            Destroy(c.GetComponent<Collider>());
            c.transform.SetParent(go.transform, false);
            var rr = c.GetComponent<Renderer>();
            rr.sharedMaterial = PM_Avatar.ShirtMaterial();
            rr.shadowCastingMode = UnityEngine.Rendering.ShadowCastingMode.Off;
            b.arm[i] = c.transform;
        }
        return b;
    }

    static void Bone(Transform cap, Vector3 a, Vector3 b, float radius)
    {
        Vector3 d = b - a;
        float len = d.magnitude;
        cap.position = (a + b) * 0.5f;
        cap.rotation = len > 0.0001f ? Quaternion.FromToRotation(Vector3.up, d / len) : Quaternion.identity;
        cap.localScale = new Vector3(radius * 2f, (len + radius * 2f) * 0.5f, radius * 2f);
    }

    void LateUpdate()
    {
        if (head == null) { head = Camera.main != null ? Camera.main.transform : null; if (head == null) return; }
        float floorY = origin != null ? origin.position.y : head.position.y - 1.6f;
        // Standing eye height = the highest seen (crouching does not shrink the body).
        eyeReal = Mathf.Max(eyeReal, Mathf.Clamp(head.position.y - floorY, 1.0f, 1.95f));
        float s = eyeReal / Mathf.Max(0.5f, eyeModel);

        // The body turns after the head (with a delay), not with every glance.
        Vector3 f = head.forward; f.y = 0;
        if (f.sqrMagnitude > 0.001f)
        {
            float target = Mathf.Atan2(f.x, f.z) * Mathf.Rad2Deg;
            float diff = Mathf.DeltaAngle(yaw, target);
            if (Mathf.Abs(diff) > 25f) yaw += diff * Mathf.Min(1f, Time.deltaTime * 4f);
        }
        Quaternion rot = Quaternion.Euler(0, yaw, 0);
        figure.localScale = Vector3.one * s;
        figure.rotation = rot;
        // The body stands a bit behind the eyes, so looking down at the board the chest does not hide it.
        float back = PM_Avatar.BodyType == 1 ? 0.21f : 0.18f;
        figure.position = head.position - Vector3.up * eyeModel * s - rot * new Vector3(0, 0, back * s);
        // ...but the head (seen only in the mirror) stays exactly where the eyes are.
        Transform headPart = figure.Find("Head");
        if (headPart != null) headPart.localPosition = new Vector3(0f, 0f, back - 0.08f);

        Vector3 right = rot * Vector3.right, fwd = rot * Vector3.forward;
        Vector3 shL = figure.TransformPoint(new Vector3(-shoulder.x, shoulder.y, shoulder.z));
        Vector3 shR = figure.TransformPoint(new Vector3(shoulder.x, shoulder.y, shoulder.z));
        Arm(shL, lh, -right, fwd, 0, 1, s);
        Arm(shR, rh, right, fwd, 2, 3, s);
    }

    void Arm(Vector3 sh, PM_Hand hand, Vector3 outward, Vector3 fwd, int upper, int lower, float s)
    {
        bool on = hand != null && hand.Wrist != null && hand.isActiveAndEnabled;
        arm[upper].gameObject.SetActive(on);
        arm[lower].gameObject.SetActive(on);
        if (!on) return;
        float L1 = 0.29f * s, L2 = 0.26f * s;
        Vector3 wrist = hand.Wrist.position;
        Vector3 to = wrist - sh;
        float dist = Mathf.Clamp(to.magnitude, 0.05f, L1 + L2 - 0.001f);
        Vector3 dir = to.normalized;
        Vector3 pole = Vector3.down + outward * 0.6f - fwd * 0.3f;
        pole = (pole - Vector3.Dot(pole, dir) * dir).normalized;
        float a = (L1 * L1 - L2 * L2 + dist * dist) / (2f * dist);
        float hh = Mathf.Sqrt(Mathf.Max(0f, L1 * L1 - a * a));
        Vector3 elbow = sh + dir * a + pole * hh;
        Bone(arm[upper], sh, elbow, 0.048f * s);
        Bone(arm[lower], elbow, wrist, 0.038f * s);
    }
}
